"use client";

import Link from "next/link";
import { useState } from "react";
import type { ReviewComment, ReviewDecision, ReviewRequestDetailDto } from "@/lib/review/types";
import { ReviewCommentForm } from "./ReviewCommentForm";

type Props = { request: ReviewRequestDetailDto; viewerMode: "author" | "reviewer" };
type Tab = "skill" | "attachments" | "comments" | "metadata";

export function ReviewRequestDetail({ request: initialRequest, viewerMode }: Props) {
  const [request, setRequest] = useState(initialRequest); const [tab, setTab] = useState<Tab>("skill"); const [decisionComment, setDecisionComment] = useState(""); const [content, setContent] = useState(initialRequest.rawContent); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const canResubmit = viewerMode === "author" && request.status === "changes_requested";
  async function decide(decision: ReviewDecision) { setBusy(true); setMessage(null); try { const response = await fetch(`/api/review-requests/${request.id}/decision`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision, comment: decisionComment || null }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "No se pudo registrar la decision"); setRequest((current) => ({ ...current, ...data.request })); setMessage("Decision registrada."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "No se pudo registrar la decision"); } finally { setBusy(false); } }
  async function resubmit() { setBusy(true); setMessage(null); try { const response = await fetch(`/api/review-requests/${request.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rawContent: content }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "No se pudo reenviar la propuesta"); setRequest((current) => ({ ...current, ...data.request })); setMessage("Propuesta reenviada para revision."); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "No se pudo reenviar la propuesta"); } finally { setBusy(false); } }
  const comments = [...request.comments].sort((a, b) => a.createdAt - b.createdAt);
  return <div>
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: "16px", marginBottom: "20px" }}><div><Link href={viewerMode === "author" ? "/dashboard/proposals" : "/dashboard/review"} style={{ fontSize: "12px", color: "var(--muted)", textDecoration: "none" }}>Volver a solicitudes</Link><h1 style={{ fontFamily: "var(--font-geist), sans-serif", fontSize: "22px", margin: "8px 0 4px", color: "var(--text)" }}>{request.name}</h1><p style={{ margin: 0, fontFamily: "var(--font-jetbrains-mono), monospace", fontSize: "12px", color: "var(--muted)" }}>{request.slug} · v{request.version}</p></div><span style={{ fontSize: "12px", color: "var(--amber)", border: "1px solid var(--amber)", borderRadius: "3px", padding: "4px 7px" }}>{request.status.replaceAll("_", " ")}</span></div>
    {viewerMode === "reviewer" && request.status === "pending" && <div style={actionPanelStyle}><textarea value={decisionComment} onChange={(event) => setDecisionComment(event.target.value)} rows={2} placeholder="Comentario general (requerido para rechazar o pedir cambios)" style={textareaStyle} /><div style={{ display: "flex", gap: "8px", marginTop: "8px" }}><button disabled={busy} onClick={() => decide("approve")} style={approveStyle}>Aprobar</button><button disabled={busy} onClick={() => decide("request_changes")} style={neutralStyle}>Pedir cambios</button><button disabled={busy} onClick={() => decide("reject")} style={rejectStyle}>Rechazar</button></div></div>}
    {canResubmit && <div style={actionPanelStyle}><div style={{ fontSize: "13px", color: "var(--muted)", marginBottom: "8px" }}>Actualiza SKILL.md y reenvia la propuesta.</div><button disabled={busy} onClick={resubmit} style={approveStyle}>Reenviar a revision</button></div>}
    {message && <p style={{ fontSize: "12px", color: message.includes(".") ? "var(--green)" : "var(--red)" }}>{message}</p>}
    <div style={{ display: "flex", gap: "4px", borderBottom: "1px solid var(--border)", marginTop: "20px" }}>{([['skill', 'SKILL.md'], ['attachments', 'Adjuntos'], ['comments', `Comentarios (${comments.length})`], ['metadata', 'Metadata']] as [Tab, string][]).map(([id, label]) => <button key={id} onClick={() => setTab(id)} style={{ ...tabStyle, color: tab === id ? "var(--text)" : "var(--muted)", borderBottomColor: tab === id ? "var(--accent)" : "transparent" }}>{label}</button>)}</div>
    <section style={contentStyle}>
      {tab === "skill" && (canResubmit ? <textarea value={content} onChange={(event) => setContent(event.target.value)} rows={24} style={{ ...textareaStyle, fontFamily: "var(--font-jetbrains-mono), monospace", fontSize: "12px" }} /> : <pre style={preStyle}>{request.rawContent}</pre>)}
      {tab === "attachments" && (request.files.length ? <div style={{ display: "grid", gap: "8px" }}>{request.files.map((file) => <div key={file.id} style={fileStyle}><strong>{file.path}</strong><span>{file.fileType} · {file.changeType}</span><pre style={{ ...preStyle, marginTop: "10px" }}>{file.content}</pre></div>)}</div> : <p style={emptyCopyStyle}>Esta propuesta no tiene archivos adjuntos.</p>)}
      {tab === "comments" && <div>{comments.length === 0 ? <p style={emptyCopyStyle}>No hay comentarios todavia.</p> : comments.map((comment) => <Comment key={comment.id} comment={comment} />)}<ReviewCommentForm requestId={request.id} onComment={(comment) => setRequest((current) => ({ ...current, comments: [...current.comments, comment] }))} /></div>}
      {tab === "metadata" && <dl style={metadataStyle}>{[["Autor", request.authorHandle ?? "Sin nombre"], ["Revisor", request.reviewerHandle ?? "Sin asignar"], ["Tipo", request.type], ["Version de esquema", request.schemaVersion], ["Enviada", formatDate(request.submittedAt)], ["Actualizada", formatDate(request.updatedAt)]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}
    </section>
  </div>;
}
function Comment({ comment }: { comment: ReviewComment }) { return <article style={{ borderBottom: "1px solid var(--border)", padding: "12px 0" }}><div style={{ display: "flex", justifyContent: "space-between", gap: "12px", fontSize: "12px" }}><strong style={{ color: "var(--text)" }}>{comment.authorHandle ?? "Usuario"}</strong><span style={{ color: "var(--faint)" }}>{formatDate(comment.createdAt)}</span></div><p style={{ color: "var(--muted)", fontSize: "13px", whiteSpace: "pre-wrap", marginBottom: 0 }}>{comment.body}</p></article>; }
function formatDate(value: number) { return new Date(value).toLocaleString("es", { dateStyle: "medium", timeStyle: "short" }); }
const actionPanelStyle: React.CSSProperties = { background: "var(--surface)", border: "1px solid var(--border)", borderRadius: "4px", padding: "12px", marginBottom: "12px" };
const textareaStyle: React.CSSProperties = { boxSizing: "border-box", width: "100%", resize: "vertical", background: "var(--bg)", color: "var(--text)", border: "1px solid var(--border)", borderRadius: "4px", padding: "9px 10px", fontFamily: "inherit", outline: "none" };
const approveStyle: React.CSSProperties = { fontSize: "12px", fontWeight: 600, color: "#fff", background: "var(--green)", border: "none", borderRadius: "4px", padding: "7px 11px", cursor: "pointer" };
const neutralStyle: React.CSSProperties = { fontSize: "12px", fontWeight: 600, color: "var(--text)", background: "var(--raised)", border: "1px solid var(--border)", borderRadius: "4px", padding: "7px 11px", cursor: "pointer" };
const rejectStyle: React.CSSProperties = { ...approveStyle, background: "var(--red)" };
const tabStyle: React.CSSProperties = { fontSize: "12px", fontWeight: 600, background: "none", border: "none", borderBottom: "2px solid", padding: "9px 10px", cursor: "pointer" };
const contentStyle: React.CSSProperties = { marginTop: "14px", background: "var(--surface)", border: "1px solid var(--border)", borderRadius: "4px", padding: "16px" };
const preStyle: React.CSSProperties = { margin: 0, whiteSpace: "pre-wrap", overflowWrap: "anywhere", fontFamily: "var(--font-jetbrains-mono), monospace", fontSize: "12px", lineHeight: 1.6, color: "var(--text)" };
const fileStyle: React.CSSProperties = { border: "1px solid var(--border)", borderRadius: "4px", padding: "10px", fontSize: "12px", color: "var(--muted)" };
const emptyCopyStyle: React.CSSProperties = { color: "var(--faint)", fontSize: "13px", textAlign: "center", padding: "20px 0" };
const metadataStyle: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: "14px", margin: 0 };
