apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skillvault.fullname" . }}
  labels:
    {{- include "skillvault.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  AUTH_KEYCLOAK_ID: {{ .Values.auth.keycloak.id | quote }}
  AUTH_KEYCLOAK_ISSUER: {{ .Values.auth.keycloak.issuer | quote }}
  AUTH_TRUST_HOST: {{ .Values.auth.trustHost | quote }}
  AUTH_URL: {{ .Values.auth.url | quote }}
{{- if .Values.mysql.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skillvault.mysql.fullname" . }}-config
  namespace: database
  labels:
    {{- include "skillvault.labels" . | nindent 4 }}
data:
  my.cnf: |
    {{- .Values.mysql.config | nindent 4 }}
{{- end }}
