apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skillvault.fullname" . }}
  labels:
    {{- include "skillvault.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTH_SECRET: {{ required "auth.secret es requerido" .Values.auth.secret | quote }}
  AUTH_KEYCLOAK_SECRET: {{ required "auth.keycloak.secret es requerido" .Values.auth.keycloak.secret | quote }}
  DATABASE_URL: {{ include "skillvault.databaseUrl" . | quote }}
{{- if .Values.mysql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skillvault.mysql.fullname" . }}
  namespace: database
  labels:
    {{- include "skillvault.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.auth.database | quote }}
  MYSQL_USER: {{ .Values.mysql.auth.username | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.auth.password | quote }}
{{- end }}
