# Override para desarrollo local (kind / minikube)
# Uso: helm install skillvault ./helm/skillvault -f helm/skillvault/values-dev.yaml --set auth.secret=xxx --set auth.keycloak.secret=xxx

image:
  repository: xnet/skillvault
  tag: "0.3.0"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  hosts:
    - host: skillvault.qa.comsatel.com.pe
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: skillvault-tls
      hosts:
        - skillvault.qa.comsatel.com.pe


resources:
  requests:
    cpu: 10m
    memory: 128Mi
    ephemeral-storage: 512Mi
  limits:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: 512Mi

auth:
  secret: PFYH3MXZlwors0hD45OmefO5NsQoSwmA
  keycloak:
    secret: PFYH3MXZlwors0hD45OmefO5NsQoSwmA

externalDatabaseUrl: "mysql://userqa:us3rq4159@skillvault-db.database.svc.cluster.local:3306/skillvault"
mysql:
  enabled: true
  auth:
    rootPassword: welcome1
    database: skillvault
    username: userqa
    password: "us3rq4159"
  persistence:
    enabled: true
