# Override para entorno QA (Kubernetes + Nginx Ingress + Cert-Manager)
# Uso: helm install skillvault ./helm/skillvault -f helm/skillvault/values-qa.yaml --set auth.secret=xxx --set auth.keycloak.secret=xxx

image:
  repository: xnet/skillvault
  tag: "0.3.0"
  pullPolicy: IfNotPresent

replicaCount: 1

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-qa"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: skillvault.qa.comsatel.com.pe
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: skillvault-qa-tls
      hosts:
        - skillvault.qa.comsatel.com.pe

auth:
  trustHost: "true"
  url: "https://skillvault.qa.comsatel.com.pe"
  keycloak:
    id: "skillvault"
    issuer: "https://oauth2.qa.comsatel.com.pe/realms/Apps"

mysql:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi
